### ISSUE TITLE
standardplots when ms ends in "/" outputs wrong file names

### ISSUE THREAD

**Issue by bmarcote** [haavee/jiveplot#11]
I thought we had fixed this, but apparently not.

If you run standardplots where the MS option (the MS path name) ends with a "/", then all output files are saved with a wrong name. Instead of the expected "{MS}-{##}.ps", they are called "-{##}.ps".

**Comment by haavee** [comment]
I think that what happened is this: 
It was fixed in master but you were using the flag_branch, which split from master before that fix and flag_branch was not sync'ed with master.

**Comment by haavee** [comment]
This issue is definitely fixed in "baseline_parser" branch, so will eventually migrate to master.
