### ISSUE TITLE
Baseline selection fails for an AARTFAAC MS

### ISSUE THREAD

**Issue by shulevski** [haavee/jiveplot#14]
Executing:
 ``jcli> bl (A12_380)A12_382``
results in: 
``the command 'bl (A12_380)A12_382' is unknown``. 
However, 
``jcli> taql ANTENNA1=380 and ANTENNA2 in [381,382]
taqlStr:  ANTENNA1=380 and ANTENNA2 in [381,382]``
works. 
The antenna entries in the MS are like:
``listAntennas:  A12_564 (564)  A12_565 (565)  A12_566 (566)  A12_567 (567)``
``listAntennas:  A12_568 (568)  A12_569 (569)  A12_570 (570)  A12_571 (571)``
etc.

**Comment by haavee** [comment]
Fixed in branch issue-14, wil eventually be merged into master

**Comment by mkuiack** [comment]
I am unable to get this branch working via singularity image. 
I have checked out the issue-14 branch locally and tried pulling the singularity images tagged jiveplot and jiveplot:latest from shub. Using Singularity version: 2.6.1-dist

I tried creating a pull request but got validation failed error. 
Could you please explain how to use this branch with singularity? I'm unable to install ppgplot locally.

**Comment by mkuiack** [comment]
I have gotten this to work now, following the following steps. 
1) delete the existing jiveplot repo
2) singularity pull shub://haavee/jiveplot:latest 
3) git clone -b issue-14 https://github.com/haavee/jiveplot.git 
4) singularity shell --bind $HOME/soft/src/jiveplot:/opt/jive --pwd $PWD haavee-jiveplot-master-latest.simg
🥳 


Why does it not work to clone the master and simply checkout the issue-14 branch ? Is there another step required.

**Comment by haavee** [comment]
Thanks Mark for solving this!

Op do 23 jul. 2020 om 14:02 schreef Mark <notifications@github.com>
