### ISSUE TITLE
Compatibility issues for Python 3.7 or higher

### ISSUE THREAD

**Issue by bmarcote** [haavee/jiveplot#18]
The current version of `jiveplot` cannot be used in Python 3.7 or higher (works fine up to 3.6) due to changes in the standard library. Relevant ones seems to be in the `re` module:
```
Changed in version 3.6: Unknown escapes in pattern consisting of '\' and an ASCII letter now are errors.
Changed in version 3.7: Unknown escapes in repl consisting of '\' and an ASCII letter now are errors.
```

The latter seems to trigger the following error when parsing any str in most of the functions (e.g. `bl`):
```
invalid escape sequence \w
```

**Comment by haavee** [comment]
I think is fixed in the `python23compat` branch, which will become the new `master` at some point
