### ISSUE TITLE
Plotting data with multiple frequency groups requires explicit data selection

### ISSUE THREAD

**Issue by kettenis** [haavee/jiveplot#23]
Plotting without explicit frequency group selection results in:
`DATA_DESC_ID 0 is unknown`
This probably shouldn't be the case. Data set is available at `eee:/data0/kettenis/VSN005598`.

**Comment by haavee** [comment]
I believe this was fixed by this commit https://github.com/haavee/jiveplot/commit/4ad574da063d309a195b8453254a9120723ad28d ; will eventually end up in `master`.
