### ISSUE TITLE
`lp` does not work in Python 3

### ISSUE THREAD

**Issue by bmarcote** [haavee/jiveplot#24]
I noticed another of the unexpected changes when moving to Python 3.8+:

```
jcli> lp
Known plot-types:
unsupported format string passed to EnumValueMeta.__format__
jcli>
```

`lp` doesn't return any value.
This has been observed in the current `issue-18` and `python23-compact` branches that are in `eee`.

**Comment by haavee** [comment]
Hmmmm I'm _reasonably_ sure this was fixed, can you check this branch https://github.com/haavee/jiveplot/tree/new-master-%231 ? That does have a fix mentioning the `lp` command in Py3.9 as far as I can see.

**Comment by bmarcote** [comment]
Totally right!
That branch has fixed it.
