### ISSUE TITLE
Jiveplot animate by time fails as 'Page' object has no attribute '_growlayout'

### ISSUE THREAD

**Issue by jaythespacehound** [haavee/jiveplot#3]
To reproduce:
on ee:
cd /data0/immer/ES089

jcli> ms es089_line.ms
ms: Current MS is 'es089_line.ms' containing 626062 rows of Spectral data for ES089 [DATA]
jcli> pt ampfreq; bl EfJb; solint 5m; avt vector; src G30.198
plotType:                 ampfreq [amplitude versus frequency]
baselines: EfJb
solint:                   300.0s
averageTime:              Vector
sources:   G30.198
jcli> pl
Query took		0.850s
Data munching took	1.595s                                                            
min/max processing took	0.000s                
drawing took	0.015s                
jcli> animate by time
Preparing  132  datasets for animation
Preparing animation took	0.123s                
Press ^C to stop the animation [0.7fps]
Traceback (most recent call last):
  File "/eee/jiveplot/command.py", line 407, in run
    quote_split(stripcomment(line)))
  File "/eee/jiveplot/command.py", line 406, in <lambda>
    map(lambda x: self.parseOneCmd(x) if not self.exit else None, \
  File "/eee/jiveplot/command.py", line 511, in parseOneCmd
    cmd.cb(args)
  File "/eee/jiveplot/jplotter.py", line 2321, in animate_fn
    j().drawFunc(page_plots, ppgplot, 0, plots.AllInOne, ncol=env().devNColor)
  File "/eee/jiveplot/jplotter.py", line 1750, in drawFunc
    plotter.drawfunc(dev, plotar, fst, onePage, **opts)
  File "/eee/jiveplot/plots.py", line 1568, in drawfunc
    page     = self.pagestyle(device, onePage, plotar, expandy=True)
  File "/eee/jiveplot/plots.py", line 1326, in pagestyle
    return Page(self, device, onePage, nplots, **kwargs)
  File "/eee/jiveplot/plots.py", line 579, in __init__
    self._growlayout(nplot, **kwargs)
AttributeError: 'Page' object has no attribute '_growlayout'
'Page' object has no attribute '_growlayout'
jcli>

**Comment by haavee** [comment]
This was fixed by this commit: https://github.com/haavee/jiveplot/commit/26701e116f419767a846bd6ba33499b72ca45adc
