### ISSUE TITLE
jplotter command line arguments

### ISSUE THREAD

**Issue by mjanssen2308** [haavee/jiveplot#4]
Allow jplotter to take command line arguments that will be executed from within the program.
I.e., instead of doing 
$ printf "<plotcmd>" | jplotter
allow the user to do
$ jplotter -c <plotcmd>

**Comment by haavee** [comment]
Hey Michael,

I did implement this about a week ago and now I'm not so sure you actually
were notified.
I committed something to github with, what I believe, a commit message
which should trigger an email to this issue's comment thread and, by
extension, you; such that you get notified about it.

But now I'm starting to wonder if that actually happened. So, did you get
an email from github about anything changing wrt to this issue? (Issue #4)

cheers,
h

**Comment by mjanssen2308** [comment]
Hi Harro,

I do not think I was actually notified.
But maybe that is due to my github settings? I do not use github that much..
Anyway, thank you for implementing this. Unfortunately, I am occupied with
other projects right now so it will take some time before I can start
playing around with the singularity image.

Best,
Michael

Am Di., 4. Dez. 2018 um 08:17 Uhr schrieb Harro Verkouter <
notifications@github.com>:

**Comment by haavee** [comment]
no worries!
I just wanted to let you know that if you request/report something, things
will eventually really happen :-)

Now that I say this, I am stil working on the flagged+averaging stuff; it
seems like I'm getting there!

Finally: I don't think it's a problem with your github settings; I know
that github triggers on special syntax in the commit message and acts
accordingly. It is most likely that my commit message did not adhere to the
regexes it looks for ...

Cheers!
h

**Comment by haavee** [comment]
Ah I see - I  created a special branch for this issue and the commit
message indeed does not adhere to the standard formats for marking it as
resolved ...

**Comment by haavee** [comment]
https://github.com/haavee/jiveplot/commit/7b4be4965b72a0153521743366962243be0fa020 closes #4
