### ISSUE TITLE
Baseline selection: order matters 

### ISSUE THREAD

**Issue by bmarcote** [haavee/jiveplot#9]
When doing a selection of a determine baseline, I found the following behavior:

> bl EfSr
baselines: EfSr

> bl SrEf
No baselines matched your selection
baselines: No baselines selected yet

> bl EfSr
baselines: EfSr

The MS contains several antennas, including "Sr" and "Ef". Depending on the order I write them, it finds the desired baseline or not. Is it the expected behavior?
I think the selection should search for both possibilities (e.g. when looking for "SrEf" -> search for the data with "SrEf" and "EfSr"), as it can give an unexpected result.

**Comment by haavee** [comment]
Yes, with a string literal like this, this happens.

The "simple" solution is to specify the baseline like this:

    bl sr(ef)

The thing is that the baseline matching code, when presented with a string  like `SrEf` it does not know where to break up the baseline into the constituent stations. You use capitalization but the software cannot _rely_ on that (e.g. LOFAR stations/baselines most definitely do *not* follow this scheme and neither can it be guaranteed for e.g. ALMA or the VLA).

Therefore the code supports `(...)` to allow the user to manually split a baseline into `X(Y)` parts  and *then* the code will match on baselines `XY` as well as `YX`

Specifically, this is a simplified form of regex sub-matching; e.g.`(ef|sr)wb` (see `help bl`) where the baseline "parser" has added the functionality to use the brackets as station split indication.

**Comment by bmarcote** [comment]
Thanks.
I knew that in all other cases I was using it, it worked as expected. I was then surprised about the behavior with this simple case. But as you said, I simplified it too much, ignoring the brackets or other conditions.
